package bpelcolegioca;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1047
public class casaPort1Client {
    public static void main(String[] args) {
        BPELColegioCAService1 bPELColegioCAService1 = new BPELColegioCAService1();
        InvokeColegioEstudiantePortType invokeColegioEstudiantePortType = bPELColegioCAService1.getCasaPort1();
        // Add your code to call the desired methods.


    }
}
