
package bpelcolegioca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "InvokeColegioEstudiantePortType",
            targetNamespace = "http://j2ee.netbeans.org/wsdl/BPELColegio/src/InvokeColegioEstudiante")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface InvokeColegioEstudiantePortType {


    /**
     *
     * @param documento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InvokeColegioEstudianteOperation")
    @WebResult(name = "respuesta", partName = "respuesta")
    public String invokeColegioEstudianteOperation(@WebParam(name = "documento", partName = "documento")
                                                   String documento);

}
